services:
  - type: web
    name: certivault-backend
    env: python
    branch: main
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "certivault:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
  
  - type: web
    name: certivault-frontend
    env: node
    branch: main
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: certivault-backend
          property: renderURL
