services:
  - type: web
    name: certivault-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend -w 4 -b 0.0.0.0:$PORT "certivault:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
  
  - type: web
    name: certivault-frontend
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm run start --prefix frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: certivault-backend
          property: renderURL
